# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    container_name: quote
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=quotedb
      - POSTGRES_DB=quotedb
    ports:
          - "5000:5432"
    volumes:
      - postgresql:/var/lib/postgresql
      # This needs explicit mapping due to https://github.com/docker-library/postgres/blob/4e48e3228a30763913ece952c611e5e9b95c8759/Dockerfile.template#L52
      - postgresql_data:/var/lib/postgresql/data

volumes:
  postgresql:
  postgresql_data:
