spring:
  jpa:
    hibernate:
      ddl-auto: none

    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
  datasource:
#    url: jdbc:postgresql://quotedb:5432/quotedb
    url: jdbc:postgresql://localhost:5000/quotedb
    username: postgres
    password: quotedb
#    url: jdbc:postgresql://localhost:5432/spring-boot-heroku-example
    driver-class-name: org.postgresql.Driver
#    schema: classpath*:schema-h2.sql
#    data: classpath*:data-h2.sql
