spring:
  jpa:
    hibernate:
      ddl-auto: none

    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        use_sql_comments: true
    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5000/quotedb
    username: postgres
    password: quotedb
    driver-class-name: org.postgresql.Driver
#    schema: classpath*:schema-h2.sql
#    data: classpath*:data-h2.sql
yahoo:
  index:
    symbol: IXIC
    full:
      symbol: ^IXIC
    nasdaq:
      full:
        symbol: ^IXIC
      symbol: IXIC
    snp:
      full:
        symbol: ^GSPC
      symbol: GSPC

quote:
  scheme: https
  url: finance.yahoo.com
  historic:
    url: query1.finance.yahoo.com
