spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true

yahoo:
  index:
    symbol: IXIC
#    symbol: GSPC
    full:
#      symbol: ^GSPC
      symbol: ^IXIC
    nasdaq:
      full:
        symbol: ^IXIC
      symbol: IXIC
    snp:
      full:
        symbol: ^GSPC
      symbol: GSPC

web:
  dailyFile: csv/daily.csv
  weeklyFile: csv/weekly.csv
  monthlyFile: csv/monthly.csv

quote:
  scheme: https
  url: finance.yahoo.com
  historic:
    url: query1.finance.yahoo.com
