spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true

quote:
  scheme: https
  url: finance.yahoo.com
  historic:
    url: query1.finance.yahoo.com
