package com.herringbone.stock.model;

// default package
// Generated Jan 8, 2014 8:09:55 PM by Hibernate Tools 3.4.0.CR1


import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Trendtype generated by hbm2java
 */
@Entity
@Table(name="trendtype")
@Builder
@Getter
@Setter
@AllArgsConstructor
@NoArgsConstructor
public class Trendtype  implements java.io.Serializable {

    @Id
    @Column(name="ID", unique=true, nullable=false)
    private long id;

    @Column(name="DESCRIPTION", length=100)
    private String description;


    @Column(name="TRENDVALUE", unique=true, nullable=false)
    private long trendvalue;

    public Trendtype(long trendvalue) {
        this.trendvalue = trendvalue;
    }

}


